//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Templates.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Templates.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank App.
        /// </summary>
        public static string BlankApp {
            get {
                return ResourceManager.GetString("BlankApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cross-platform template for building cross-platform, native mobile apps for iOS, Android, and Universal Windows Platform.
        ///    
        ///Use the native user interface approach to create UIs for each platform, or use Xamarin.Forms to create cross-platform, native UIs in XAML..
        /// </summary>
        public static string BlankAppDescription {
            get {
                return ResourceManager.GetString("BlankAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank App (XAML).
        /// </summary>
        public static string BlankAppXaml {
            get {
                return ResourceManager.GetString("BlankAppXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cross platform template for building apps with Xamarin.Forms entirely based on XAML..
        /// </summary>
        public static string BlankAppXamlDescription {
            get {
                return ResourceManager.GetString("BlankAppXamlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host in the cloud.
        /// </summary>
        public static string HostInTheCloud {
            get {
                return ResourceManager.GetString("HostInTheCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Detail.
        /// </summary>
        public static string MasterDetail {
            get {
                return ResourceManager.GetString("MasterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project template for creating cross-platform, native mobile apps for iOS, Android, and Universal Windows Platform (UWP) with master-detail navigation pattern.
        ///
        ///Use the native user interface approach to create UIs for each platform, or use Xamarin.Forms to create cross-platform, native UIs in XAML..
        /// </summary>
        public static string MasterDetailDescription {
            get {
                return ResourceManager.GetString("MasterDetailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure.
        /// </summary>
        public static string MicrosoftAzure {
            get {
                return ResourceManager.GetString("MicrosoftAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native.
        /// </summary>
        public static string Native {
            get {
                return ResourceManager.GetString("Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Class Library (PCL).
        /// </summary>
        public static string PCL {
            get {
                return ResourceManager.GetString("PCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a template:.
        /// </summary>
        public static string SelectATemplate {
            get {
                return ResourceManager.GetString("SelectATemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine Windows SDK platform version..
        /// </summary>
        public static string SetWindowsUniversalPlatformVersion_FailedToDeterminePlatformVersion {
            get {
                return ResourceManager.GetString("SetWindowsUniversalPlatformVersion_FailedToDeterminePlatformVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Project.
        /// </summary>
        public static string SharedProjects {
            get {
                return ResourceManager.GetString("SharedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Sharing Strategy.
        /// </summary>
        public static string Sharing {
            get {
                return ResourceManager.GetString("Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Technology.
        /// </summary>
        public static string UITechnology {
            get {
                return ResourceManager.GetString("UITechnology", resourceCulture);
            }
        }
    }
}
