//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Templates.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Templates.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AndroidDialog_Cancel {
            get {
                return ResourceManager.GetString("AndroidDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Android app with an Activity class and empty layout file..
        /// </summary>
        public static string AndroidViewModel_BlankApp_Description {
            get {
                return ResourceManager.GetString("AndroidViewModel_BlankApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank App.
        /// </summary>
        public static string AndroidViewModel_BlankApp_Name {
            get {
                return ResourceManager.GetString("AndroidViewModel_BlankApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Android app that uses a panel on the left side to present navigation options. Use this as an alternative to tabs if you have lots of navigation targets and want to maximize screen space..
        /// </summary>
        public static string AndroidViewModel_NavigationDrawerApp_Description {
            get {
                return ResourceManager.GetString("AndroidViewModel_NavigationDrawerApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Drawer App.
        /// </summary>
        public static string AndroidViewModel_NavigationDrawerApp_Name {
            get {
                return ResourceManager.GetString("AndroidViewModel_NavigationDrawerApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Android app with a single Activity and simple AXML layout file. Use this basic template as a starting point for any Android app..
        /// </summary>
        public static string AndroidViewModel_SingleViewApp_Description {
            get {
                return ResourceManager.GetString("AndroidViewModel_SingleViewApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single View App.
        /// </summary>
        public static string AndroidViewModel_SingleViewApp_Name {
            get {
                return ResourceManager.GetString("AndroidViewModel_SingleViewApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Android app that uses tab icons at the bottom of the screen for navigation. Use this if your app will have few navigation targets that will be frequently switched between..
        /// </summary>
        public static string AndroidViewModel_TabbedApp_Description {
            get {
                return ResourceManager.GetString("AndroidViewModel_TabbedApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed App.
        /// </summary>
        public static string AndroidViewModel_TabbedApp_Name {
            get {
                return ResourceManager.GetString("AndroidViewModel_TabbedApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank App.
        /// </summary>
        public static string BlankApp {
            get {
                return ResourceManager.GetString("BlankApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project template for building Xamarin.Forms XAML-based cross-platform native mobile apps for iOS, Android, and Universal Windows Platform..
        /// </summary>
        public static string BlankAppDescription {
            get {
                return ResourceManager.GetString("BlankAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank App (XAML).
        /// </summary>
        public static string BlankAppXaml {
            get {
                return ResourceManager.GetString("BlankAppXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cross platform template for building apps with Xamarin.Forms entirely based on XAML..
        /// </summary>
        public static string BlankAppXamlDescription {
            get {
                return ResourceManager.GetString("BlankAppXamlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CrossPlatformDialog_Cancel {
            get {
                return ResourceManager.GetString("CrossPlatformDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Azure Mobile Apps backend project.
        /// </summary>
        public static string HostInTheCloud {
            get {
                return ResourceManager.GetString("HostInTheCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        public static string iOS {
            get {
                return ResourceManager.GetString("iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string IOSDialog_Cancel {
            get {
                return ResourceManager.GetString("IOSDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An iOS app with an empty UIViewController and no Storyboard file..
        /// </summary>
        public static string IOSViewModel_BlankApp_Description {
            get {
                return ResourceManager.GetString("IOSViewModel_BlankApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank App.
        /// </summary>
        public static string IOSViewModel_BlankApp_Name {
            get {
                return ResourceManager.GetString("IOSViewModel_BlankApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An iOS app that uses a split view and the master-detail navigation pattern. Use this if your app will display a list of data that will show more detail when an item is selected..
        /// </summary>
        public static string IOSViewModel_MasterDetailApp_Description {
            get {
                return ResourceManager.GetString("IOSViewModel_MasterDetailApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master-Detail App.
        /// </summary>
        public static string IOSViewModel_MasterDetailApp_Name {
            get {
                return ResourceManager.GetString("IOSViewModel_MasterDetailApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An iOS app with a Storyboard file and single UIViewController. Use this basic template as a starting point for any iOS app..
        /// </summary>
        public static string IOSViewModel_SingleViewApp_Description {
            get {
                return ResourceManager.GetString("IOSViewModel_SingleViewApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single View App.
        /// </summary>
        public static string IOSViewModel_SingleViewApp_Name {
            get {
                return ResourceManager.GetString("IOSViewModel_SingleViewApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An iOS app that uses tab icons at the bottom of the screen for navigation. Use this if your app will have different content categories that will be frequently switched between..
        /// </summary>
        public static string IOSViewModel_TabbedApp_Description {
            get {
                return ResourceManager.GetString("IOSViewModel_TabbedApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed App.
        /// </summary>
        public static string IOSViewModel_TabbedApp_Name {
            get {
                return ResourceManager.GetString("IOSViewModel_TabbedApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed.
        /// </summary>
        public static string MasterDetail {
            get {
                return ResourceManager.GetString("MasterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project template for creating Xamarin.Forms XAML-based cross-platform native mobile apps for iOS, Android, and Universal Windows Platform (UWP) with tabbed navigation pattern..
        /// </summary>
        public static string MasterDetailDescription {
            get {
                return ResourceManager.GetString("MasterDetailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Backend.
        /// </summary>
        public static string MicrosoftAzure {
            get {
                return ResourceManager.GetString("MicrosoftAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native.
        /// </summary>
        public static string Native {
            get {
                return ResourceManager.GetString("Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Standard.
        /// </summary>
        public static string PCL {
            get {
                return ResourceManager.GetString("PCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a template:.
        /// </summary>
        public static string SelectATemplate {
            get {
                return ResourceManager.GetString("SelectATemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine Windows SDK platform version..
        /// </summary>
        public static string SetWindowsUniversalPlatformVersion_FailedToDeterminePlatformVersion {
            get {
                return ResourceManager.GetString("SetWindowsUniversalPlatformVersion_FailedToDeterminePlatformVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Project.
        /// </summary>
        public static string SharedProjects {
            get {
                return ResourceManager.GetString("SharedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Sharing Strategy.
        /// </summary>
        public static string Sharing {
            get {
                return ResourceManager.GetString("Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Technology.
        /// </summary>
        public static string UITechnology {
            get {
                return ResourceManager.GetString("UITechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows (UWP).
        /// </summary>
        public static string UWP {
            get {
                return ResourceManager.GetString("UWP", resourceCulture);
            }
        }
    }
}
